language: python

python:
  - 2.6
  - 2.7

install:
  - pip install flake8 --use-mirrors
  - pip install -q -r requirements.txt --use-mirrors
  - pip install -e . --use-mirrors

script:
  - flake8 --max-line-length=100 .
